// leepa overrides

user_pref("accessibility.typeaheadfind", false);
user_pref("browser.ctrlTab.sortByRecentlyUsed", false);
user_pref("browser.display.use_system_colors", true);
user_pref("browser.download.alwaysOpenPanel", true);
user_pref("browser.download.useDownloadDir", true);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.enabled", true);
user_pref("browser.search.suggest.enabled", true);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.page", 3);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.tabs.firefox-view", false);
user_pref("browser.tabs.tabmanager.enabled", false);
user_pref("browser.urlbar.suggest.searches", true);
// user_pref("cookiebanners.service.mode", 2);
// user_pref("cookiebanners.service.mode.privateBrowsing", 2);
user_pref("extensions.formautofill.addresses.enabled", false);
user_pref("extensions.formautofill.creditCards.available", false);
user_pref("extensions.formautofill.creditCards.enabled", false);
user_pref("extensions.pocket.api", "0.0.0.0");
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.pocket.onSaveRecs", false);
user_pref("extensions.pocket.showHome", false);
user_pref("extensions.pocket.site", "0.0.0.0");
user_pref("extensions.unifiedExtensions.enabled", false);
user_pref("general.autoScroll", true);
user_pref("gfx.direct3d11.reuse-decoder-device", false);
user_pref("gfx.webrender.all", true);
user_pref("intl.accept_languages", "pl, en-US, en");
user_pref("layout.css.visited_links_enabled", true);
user_pref("media.eme.enabled", true);
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("media.wmf.zero-copy-nv12-texture", false);
user_pref("network.cookie.lifetimePolicy", 0);
user_pref("privacy.cpd.history", false);
user_pref("privacy.cpd.sessions", false);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", false);
user_pref("services.sync.prefs.sync-seen.browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("signon.rememberSignons", false);
user_pref("webgl.disabled", false);
